package com.tfg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PrescripcionFisica implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public PrescripcionFisica() {
	}

}