package com.tfg;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SeguimientoMedico implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public SeguimientoMedico() {
	}

}