spring.application.name=app-web
# Nombre de la aplicación y puerto donde se ejecuta Spring Boot
server.port=9090

# Conexion entre Spring Boot y jBPM
# jBPM/KIE Server está en 8080
kieserver.url=${KIESERVER_URL}
# Spring Boot llama a KIE Server usando wbadmin
kieserver.user=${KIESERVER_USER}
kieserver.pwd=${KIESERVER_PASSWORD}
# Busca proceso dentro del contenedor KIE
# Contenedor KIE
kieserver.container=${KIESERVER_CONTAINER}

# Proceso que arranca
# Id EXACTO del proceso (míralo en "Definiciones del proceso")
process.id=${PROCESS_ID}

# Usuario de trabajo para tareas (el mismo que pusiste como Actor)
app.user=wbadmin

# ==== Configuración correo ====
# Usada por EmailService
spring.mail.host=${MAIL_HOST}
# Usa SMTP en el puerto MAIL_PORT
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Usa autenticación y STARTTLS para cifrar la conexión
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Dirección que aparecerá como remitente
spring.mail.from=${MAIL_FROM}

# KAFKA 
# Puerto donde Spring boot conecta a kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

# EmailKafkaProducer manda EventoEmail al topic emails
# Serializador JSON (enviar objetos) - KAFKA PRODUCER
# Cuando Spring Boot envía mensaje a kafka
# Para pasar de string a bytes -> La clave se convierte en texto
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# Tu objeto Java (EventoEmail) se convierte en JSON y despues a bytes -> El objeto EventoEmail se convierte en JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Cuando kafka recibe un mensaje
# KAFKA CONSUMER
# Convierte bytes a string -> Convierte la clave desde texto
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# Convierte JSON a objeto Java
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Solo se fía de / acepta clases en ese paquete
spring.kafka.consumer.properties.spring.json.trusted.packages=com.tfg.model
# Cuando llegue JSON conviertelo a EventoEmail por defecto
spring.kafka.consumer.properties.spring.json.value.default.type=com.tfg.model.EventoEmail
# Los consumers se organizan por grupos
spring.kafka.consumer.group-id=email-worker
# Así podemos ver mensajes antiguos
spring.kafka.consumer.auto-offset-reset=latest

# BASE DE DATOS POSTGRESQL
# SpringBoot se conecta a PostgreSQL
# Host:puerto/bbdd
spring.datasource.url=${DB_URL}
# User y contraseña
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Si creas una entidad Java nueva, Hibernate intenta crear/actualizar su tabla en PostgreSQL.
# Hibernate ajusta tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
# Para ver en consola consultas SQL
spring.jpa.show-sql=false

# Lo usamos para construir enlaces dentro del mail
# Para confirmacion del paciente
app.base-url=${APP_BASE_URL}
# API REST de resúmenes
resumen-api.url=${RESUMEN_API_URL}